/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-09-18 03:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850415545L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <!-- jstl 가져오기 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 여러 기능이 있는 함수 가져오기 -->\r\n");
      out.write("\r\n");
      out.write("<!-- contextPath 저장 -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 받아온 것 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- controller와 resolver를 거쳐 jsp 파일로 오게됨 -->\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write(" \t \t<h2>Spring MVC03</h2>\r\n");
      out.write("  \t\t<div class=\"panel panel-default\">\r\n");
      out.write("    \t\t<div class=\"panel-heading\">Board</div>\r\n");
      out.write("    \t\t<div class=\"panel-body\">\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join.do\" method=\"post\">\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t<!-- db로 넘어갈 비밀번호 input 태그 -->\r\n");
      out.write("    \t\t\t<!-- 두개의 pw1, pw2를 memPW에 담아올 수 없음 > hidden 타입의 태그 생성 value 값이 없음 > 두 개의 비밀번호가 일치했을 때 value 값이 채워짐  -->\r\n");
      out.write("    \t\t\t<input type=\"hidden\" name=\"memPw\" id=\"memPw\" value=\"\">\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t<table class=\"table table-bordered\" style=\"text-align:center; border:1px solid #dddddd\">\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px; vertical-align:middle;\">아이디</td>\r\n");
      out.write("    \t\t\t\t\t<!-- required=\"required\" : 무조건 입력하도록..(유효성 검사) -->\r\n");
      out.write("    \t\t\t\t\t<td><input type=\"text\" required=\"required\" name=\"memId\" id=\"memId\" class = \"form-control\" maxlength=\"20\" placeholder=\"아이디를 입력하세요\"></td>\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px;\"><button type=\"button\" onclick=\"idCheck()\" class=\"btn btn-sm btn-default\">중복확인</button></td>\r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px; vertical-align:middle;\">비밀번호</td>\r\n");
      out.write("    \t\t\t\t\t<td colspan=\"2\"><input required=\"required\" type=\"password\" onkeyup=\"pwCheck()\" name=\"memPW1\" id=\"memPW1\" class = \"form-control\" maxlength=\"20\" placeholder=\"비밀번호를 입력하세요\"></td>\r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px; vertical-align:middle;\">비밀번호 확인</td>\r\n");
      out.write("    \t\t\t\t\t<td colspan=\"2\"><input type=\"password\" required=\"required\" onkeyup=\"pwCheck()\" name=\"memPW2\" id=\"memPW2\" class = \"form-control\" maxlength=\"20\" placeholder=\"비밀번호를 확인하세요\"></td>\r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px; vertical-align:middle;\">이름</td>\r\n");
      out.write("    \t\t\t\t\t<td colspan=\"2\"><input type=\"text\" required=\"required\" name=\"memName\" id=\"memName\" class = \"form-control\" maxlength=\"20\" placeholder=\"이름을 입력하세요\"></td>\r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px; vertical-align:middle;\">나이</td>\r\n");
      out.write("    \t\t\t\t\t<td colspan=\"2\"><input type=\"number\" required=\"required\" name=\"memAge\" id=\"memAge\" class = \"form-control\" maxlength=\"20\" placeholder=\"나이를 입력하세요\"></td>\r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<tr>\r\n");
      out.write("\t\t               <td style=\"width: 110px; vertical-align: middle;\">성별</td>\r\n");
      out.write("\t\t               <td colspan=\"2\">\r\n");
      out.write("\t\t                  <div class=\"form-group\" style=\"text-align: center; margin: 0 auto;\">\r\n");
      out.write("\t\t                     <div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t                        <label class=\"btn btn-default active\">\r\n");
      out.write("\t\t                           <input type=\"radio\" id=\"memGender\" name=\"memGender\" autocomplete=\"off\" value=\"남자\" checked=\"checked\"> 남자    \r\n");
      out.write("\t\t                        </label>\r\n");
      out.write("\t\t                        <label class=\"btn btn-default\">\r\n");
      out.write("\t\t                           <input type=\"radio\" id=\"memGender\" name=\"memGender\" autocomplete=\"off\" value=\"여자\" > 여자\r\n");
      out.write("\t\t                        </label>\r\n");
      out.write("\t\t                     </div>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t\t               </td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("    \t\t\t\t\t<td style=\"width:110px; vertical-align:middle;\">이메일</td>\r\n");
      out.write("    \t\t\t\t\t<td colspan=\"2\"><input type=\"email\" required=\"required\" name=\"memEmail\" id=\"memEmail\" class = \"form-control\" maxlength=\"50\" placeholder=\"이메일을 입력하세요\"></td>\r\n");
      out.write("    \t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"pwMessage\" style=\"color:red; position: absolute; top: 50%; transform: translateY(-50%); right: 115px; text-align: right;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class =\"btn btn-default btn-sm pull-right\" value=\"취소\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class =\"btn btn-default btn-sm pull-right\" value=\"등록\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t</table>    \t\t\r\n");
      out.write("    \t\t</form>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"panel-footer\">스프링 게시판 - 송은지</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  \t<!-- Modal (idCheck) -->\r\n");
      out.write("\t  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t    <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-content\" id=\"checkType\">\r\n");
      out.write("\t        <div class=\"modal-header panel-heading\">\r\n");
      out.write("\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t          <h4 class=\"modal-title\">메세지 확인</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"modal-body\">\r\n");
      out.write("\t          <p id=\"checkMessage\"></p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"modal-footer\">\r\n");
      out.write("\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>      \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\t\r\n");
      out.write("\t  \r\n");
      out.write("  \t<!-- Modal (join error)-->\r\n");
      out.write("\t  <div class=\"modal fade\" id=\"myMessage\" role=\"dialog\">\r\n");
      out.write("\t    <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-content\" id=\"messageType\">\r\n");
      out.write("\t        <div class=\"modal-header panel-heading\">\r\n");
      out.write("\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t          <!--  memberController에서 회원가입 실패시 msgType과 msg를 보냄  -->\r\n");
      out.write("\t          <h4 class=\"modal-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"modal-body\">\r\n");
      out.write("\t          <p id=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"modal-footer\">\r\n");
      out.write("\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>      \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction idCheck() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar memId = $(\"#memId\").val();  // iuput에 쓴 값을 가져옴\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 아이디 중복 체크, 자동완성 등은 비동기 방식 많이 사용\r\n");
      out.write("\t\t\t// 입력할 때마다 서버로부터 값을 받아와서 새로고침 없이 바로 보여줌\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/idCheck.do\",  // el, jstl은 java 언어가 아님 (표현식)\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {\"memId\":memId},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t// url에 보낸 data의 결과값(data)을 받아옴\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 중복유무 확인 --> data = 1 - 사용가능, 0 - 사용불가능\r\n");
      out.write("\t\t\t\t\tif(data == 1){\r\n");
      out.write("\t\t\t\t\t\t$(\"#checkMessage\").text(\"사용 가능한 아이디입니다.\");   // 선택한 요소에 글자를 넣어줌\r\n");
      out.write("\t\t\t\t\t\t$(\"#checkType\").attr(\"class\", \"modal-content panel-success\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#checkMessage\").text(\"사용할 수 없는 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#checkType\").attr(\"class\", \"modal-content panel-warning\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#myModal\").modal(\"show\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){ alert(\"error\"); }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction pwCheck() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar memPW1 = $(\"#memPW1\").val();\r\n");
      out.write("\t\t\tvar memPW2 = $(\"#memPW2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (memPW1 != memPW2) {\r\n");
      out.write("\t\t\t\t$(\"#pwMessage\").html(\"비밀번호 확인이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#memPw\").val(memPW1);   // memPW1과 memPW2 일치 시, hidden input 태그 value안에 비밀번호 저장\r\n");
      out.write("\t\t\t\t$(\"#pwMessage\").html(\"\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t// .ready - 페이지가 다 로딩될 때까지 기다렸다가 안에 있는 기능을 실행하겠다\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty msgType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("\t\t\t\t// msgType이 비어있지 않을 경우 (회원가입 실패) - el식\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgType eq \"실패 메세지\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("\t\t\t\t\t// msgType이 \"실패 메세지\"일 경우\r\n");
      out.write("\t\t\t\t\t$(\"#messageType\").attr(\"class\", \"modal-content panel-warning\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#myMessage\").modal(\"show\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/joinForm.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/member/joinForm.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/joinForm.jsp(9,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
