SELECT * FROM BOARD;

INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('화요일', 'ㅠㅠ', '바구니');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('집가고싶다', '슬퍼요', '햄햄');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('금요일언제와', '빨리와', '멈멈멈');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('영화보러갈까', '고민중....', '춘식');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('-_-', 'ㄱ-......', '커햄');

DELETE FROM BOARD WHERE IDX=6;

SELECT * FROM MEMBER;

DROP TABLE AUTH;
DROP TABLE MEMBER;