-- SQL 문장 작성 --

DROP TABLE BOARD;

-- 게시판 --
CREATE TABLE BOARD(
	-- VO에 있는 필드명과 테이블의 컬럼명이 똑같아야함 --
	
	-- NUMBER(oracle) --> int(MySQL) --
	-- AUTO_INCREMENT : 값을 안 넣어도 알아서 1씩 증가해서 들어감 (oracle - SEQUENCE) --
	IDX int NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(20) NOT NULL,  -- 해당 글 작성자만 수정/삭제 -
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
 	-- DATE(oracle) --> DATETIME(MySQL) 디폴트로 INSERT 당시의 시간 값이 들어감 --
	INDATE DATETIME DEFAULT NOW(),
	COUNT int DEFAULT 0,
	
	PRIMARY KEY(IDX)  -- IDX를 PK로 --
	); 
	
	
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('안녕하세요?','반갑습니다~','햄미');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('오늘은 수요일','주말 언제 오지?','멈뭄미');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('집가고싶다','ㅈㄱㄴ','애옹');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('배고프다','흠...','햄미');
INSERT INTO BOARD(TITLE, CONTENT, WRITER) VALUES('Hihihihi','반갑습니다~','햄미');

SELECT * FROM BOARD;

DROP TABLE AUTH;
DROP TABLE MEMBER;

-- 회원 테이블 --
CREATE TABLE MEMBER(
	MEMIDX INT NOT NULL,  -- AUTO_INCREMENT 설정 시 자동으로 PK가 됨 --
	MEMID VARCHAR(20) NOT NULL,
	MEMPW VARCHAR(68) NOT NULL,
	MEMNAME VARCHAR(20) NOT NULL,
	MEMAGE INT,
	MEMGENDER VARCHAR(20),
	MEMEMAIL VARCHAR(50),
	MEMPROFILE VARCHAR(50),
	PRIMARY KEY(MEMID)
);

-- 권한 데이블
-- Spring Security에서는 member 테이블 안에 반드시 권한이 있어야 한다
-- 사용하지 않더라도 넣어주자!

CREATE TABLE AUTH(
	NO INT NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(50) NOT NULL,
	AUTH VARCHAR(50) NOT NULL,
	PRIMARY KEY(NO),
	CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY(MEMID)   -- MEMID에 FK 설정 --
	REFERENCES MEMBER(MEMID)  -- MEMBER TABLE의 MEMID를 참조하여 AUTH TABLE의 MEMID FK 설정 --
);

INSERT INTO MEMBER(MEMID, MEMPW, MEMNAME, MEMAGE, MEMGENDER, MEMEMAIL, MEMPROFILE)
VALUES('admin', '1234', '관리자', 20, '여자', 'admin@gmail.com','');

SELECT * FROM MEMBER;
SELECT * FROM AUTH;
